"""Add analyzer core

Revision ID: 0003_analyzer_core
Revises: 0002_project_source_catalog
Create Date: 2026-07-30 11:47:32.013936
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_analyzer_core"
down_revision: str | None = "0002_project_source_catalog"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dependencies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=True),
        sa.Column("source_kind", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("source_name", sa.String(length=2048), nullable=False),
        sa.Column("target_kind", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("target_name", sa.String(length=2048), nullable=False),
        sa.Column("relation", sa.String(length=64), nullable=False),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.Column("details_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dependencies_project_id"), "dependencies", ["project_id"], unique=False
    )
    op.create_index(
        "ix_dependencies_project_source",
        "dependencies",
        ["project_id", "source_name"],
        unique=False,
    )
    op.create_index(
        "ix_dependencies_project_target",
        "dependencies",
        ["project_id", "target_name"],
        unique=False,
    )
    op.create_index(op.f("ix_dependencies_relation"), "dependencies", ["relation"], unique=False)
    op.create_index(
        op.f("ix_dependencies_source_file_id"), "dependencies", ["source_file_id"], unique=False
    )
    op.create_table(
        "metadata_objects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=64), nullable=True),
        sa.Column("kind", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("full_name", sa.String(length=2048), nullable=False),
        sa.Column("parent_full_name", sa.String(length=2048), nullable=True),
        sa.Column("synonym", sa.String(length=1024), nullable=True),
        sa.Column("properties_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "full_name", name="uq_metadata_project_full_name"),
    )
    op.create_index(
        op.f("ix_metadata_objects_full_name"), "metadata_objects", ["full_name"], unique=False
    )
    op.create_index(op.f("ix_metadata_objects_kind"), "metadata_objects", ["kind"], unique=False)
    op.create_index(op.f("ix_metadata_objects_name"), "metadata_objects", ["name"], unique=False)
    op.create_index(
        op.f("ix_metadata_objects_parent_full_name"),
        "metadata_objects",
        ["parent_full_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_metadata_objects_project_id"), "metadata_objects", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_metadata_objects_source_file_id"),
        "metadata_objects",
        ["source_file_id"],
        unique=False,
    )
    op.create_index(op.f("ix_metadata_objects_uuid"), "metadata_objects", ["uuid"], unique=False)
    op.create_index(
        "ix_metadata_project_kind_name",
        "metadata_objects",
        ["project_id", "kind", "name"],
        unique=False,
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=False),
        sa.Column("metadata_object_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("full_name", sa.String(length=2048), nullable=False),
        sa.Column("module_kind", sa.String(length=96), nullable=False),
        sa.Column("owner_kind", sa.String(length=96), nullable=True),
        sa.Column("owner_name", sa.String(length=512), nullable=True),
        sa.Column("directives_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["metadata_object_id"], ["metadata_objects.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_file_id", name="uq_modules_source_file"),
    )
    op.create_index(op.f("ix_modules_full_name"), "modules", ["full_name"], unique=False)
    op.create_index(
        op.f("ix_modules_metadata_object_id"), "modules", ["metadata_object_id"], unique=False
    )
    op.create_index(op.f("ix_modules_module_kind"), "modules", ["module_kind"], unique=False)
    op.create_index(op.f("ix_modules_name"), "modules", ["name"], unique=False)
    op.create_index(op.f("ix_modules_owner_kind"), "modules", ["owner_kind"], unique=False)
    op.create_index(op.f("ix_modules_owner_name"), "modules", ["owner_name"], unique=False)
    op.create_index(op.f("ix_modules_project_id"), "modules", ["project_id"], unique=False)
    op.create_index(
        "ix_modules_project_owner",
        "modules",
        ["project_id", "owner_kind", "owner_name"],
        unique=False,
    )
    op.create_index(op.f("ix_modules_source_file_id"), "modules", ["source_file_id"], unique=False)
    op.create_table(
        "symbols",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("is_export", sa.Boolean(), nullable=False),
        sa.Column("directive", sa.String(length=128), nullable=True),
        sa.Column("region", sa.String(length=512), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.Column("parameters_json", sa.Text(), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["module_id"], ["modules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_symbols_module_id"), "symbols", ["module_id"], unique=False)
    op.create_index(
        "ix_symbols_module_name", "symbols", ["module_id", "normalized_name"], unique=False
    )
    op.create_index(op.f("ix_symbols_name"), "symbols", ["name"], unique=False)
    op.create_index(op.f("ix_symbols_project_id"), "symbols", ["project_id"], unique=False)
    op.create_index(
        "ix_symbols_project_name", "symbols", ["project_id", "normalized_name"], unique=False
    )
    op.create_index(op.f("ix_symbols_source_file_id"), "symbols", ["source_file_id"], unique=False)
    op.create_table(
        "call_sites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=False),
        sa.Column("caller_symbol_id", sa.Integer(), nullable=True),
        sa.Column("resolved_symbol_id", sa.Integer(), nullable=True),
        sa.Column("callee_name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column("qualifier", sa.String(length=1024), nullable=True),
        sa.Column("full_name", sa.String(length=1536), nullable=False),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.Column("column", sa.Integer(), nullable=False),
        sa.Column("resolution", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["caller_symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resolved_symbol_id"], ["symbols.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_call_sites_caller_symbol_id"), "call_sites", ["caller_symbol_id"], unique=False
    )
    op.create_index(op.f("ix_call_sites_project_id"), "call_sites", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_call_sites_resolved_symbol_id"), "call_sites", ["resolved_symbol_id"], unique=False
    )
    op.create_index(
        op.f("ix_call_sites_source_file_id"), "call_sites", ["source_file_id"], unique=False
    )
    op.create_index(
        "ix_calls_project_target", "call_sites", ["project_id", "normalized_name"], unique=False
    )
    op.create_table(
        "queries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("tables_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_queries_project_id"), "queries", ["project_id"], unique=False)
    op.create_index("ix_queries_project_kind", "queries", ["project_id", "kind"], unique=False)
    op.create_index(op.f("ix_queries_source_file_id"), "queries", ["source_file_id"], unique=False)
    op.create_index(op.f("ix_queries_symbol_id"), "queries", ["symbol_id"], unique=False)
    op.create_index(op.f("ix_queries_text_hash"), "queries", ["text_hash"], unique=False)
    op.create_table(
        "references",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("source_file_id", sa.Integer(), nullable=False),
        sa.Column("symbol_id", sa.Integer(), nullable=True),
        sa.Column("source_metadata_name", sa.String(length=2048), nullable=True),
        sa.Column("metadata_object_id", sa.Integer(), nullable=True),
        sa.Column("target_kind", sa.String(length=96), nullable=False),
        sa.Column("target_name", sa.String(length=512), nullable=False),
        sa.Column("target_full_name", sa.String(length=1024), nullable=False),
        sa.Column("normalized_target", sa.String(length=1024), nullable=False),
        sa.Column("relation", sa.String(length=64), nullable=False),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("raw_value", sa.String(length=2048), nullable=True),
        sa.ForeignKeyConstraint(
            ["metadata_object_id"], ["metadata_objects.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_file_id"], ["source_files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symbol_id"], ["symbols.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_references_metadata_object_id"), "references", ["metadata_object_id"], unique=False
    )
    op.create_index(op.f("ix_references_project_id"), "references", ["project_id"], unique=False)
    op.create_index(
        "ix_references_project_target",
        "references",
        ["project_id", "normalized_target"],
        unique=False,
    )
    op.create_index(
        op.f("ix_references_source_file_id"), "references", ["source_file_id"], unique=False
    )
    op.create_index(op.f("ix_references_symbol_id"), "references", ["symbol_id"], unique=False)
    op.add_column(
        "projects", sa.Column("last_analyzed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("projects", sa.Column("profile_json", sa.Text(), nullable=True))
    op.add_column(
        "source_files", sa.Column("analyzed_checksum", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "source_files", sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("source_files", sa.Column("analysis_error", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_files", "analysis_error")
    op.drop_column("source_files", "analyzed_at")
    op.drop_column("source_files", "analyzed_checksum")
    op.drop_column("projects", "profile_json")
    op.drop_column("projects", "last_analyzed_at")
    op.drop_index(op.f("ix_references_symbol_id"), table_name="references")
    op.drop_index(op.f("ix_references_source_file_id"), table_name="references")
    op.drop_index("ix_references_project_target", table_name="references")
    op.drop_index(op.f("ix_references_project_id"), table_name="references")
    op.drop_index(op.f("ix_references_metadata_object_id"), table_name="references")
    op.drop_table("references")
    op.drop_index(op.f("ix_queries_text_hash"), table_name="queries")
    op.drop_index(op.f("ix_queries_symbol_id"), table_name="queries")
    op.drop_index(op.f("ix_queries_source_file_id"), table_name="queries")
    op.drop_index("ix_queries_project_kind", table_name="queries")
    op.drop_index(op.f("ix_queries_project_id"), table_name="queries")
    op.drop_table("queries")
    op.drop_index("ix_calls_project_target", table_name="call_sites")
    op.drop_index(op.f("ix_call_sites_source_file_id"), table_name="call_sites")
    op.drop_index(op.f("ix_call_sites_resolved_symbol_id"), table_name="call_sites")
    op.drop_index(op.f("ix_call_sites_project_id"), table_name="call_sites")
    op.drop_index(op.f("ix_call_sites_caller_symbol_id"), table_name="call_sites")
    op.drop_table("call_sites")
    op.drop_index(op.f("ix_symbols_source_file_id"), table_name="symbols")
    op.drop_index("ix_symbols_project_name", table_name="symbols")
    op.drop_index(op.f("ix_symbols_project_id"), table_name="symbols")
    op.drop_index(op.f("ix_symbols_name"), table_name="symbols")
    op.drop_index("ix_symbols_module_name", table_name="symbols")
    op.drop_index(op.f("ix_symbols_module_id"), table_name="symbols")
    op.drop_table("symbols")
    op.drop_index(op.f("ix_modules_source_file_id"), table_name="modules")
    op.drop_index("ix_modules_project_owner", table_name="modules")
    op.drop_index(op.f("ix_modules_project_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_owner_name"), table_name="modules")
    op.drop_index(op.f("ix_modules_owner_kind"), table_name="modules")
    op.drop_index(op.f("ix_modules_name"), table_name="modules")
    op.drop_index(op.f("ix_modules_module_kind"), table_name="modules")
    op.drop_index(op.f("ix_modules_metadata_object_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_full_name"), table_name="modules")
    op.drop_table("modules")
    op.drop_index("ix_metadata_project_kind_name", table_name="metadata_objects")
    op.drop_index(op.f("ix_metadata_objects_uuid"), table_name="metadata_objects")
    op.drop_index(op.f("ix_metadata_objects_source_file_id"), table_name="metadata_objects")
    op.drop_index(op.f("ix_metadata_objects_project_id"), table_name="metadata_objects")
    op.drop_index(op.f("ix_metadata_objects_parent_full_name"), table_name="metadata_objects")
    op.drop_index(op.f("ix_metadata_objects_name"), table_name="metadata_objects")
    op.drop_index(op.f("ix_metadata_objects_kind"), table_name="metadata_objects")
    op.drop_index(op.f("ix_metadata_objects_full_name"), table_name="metadata_objects")
    op.drop_table("metadata_objects")
    op.drop_index(op.f("ix_dependencies_source_file_id"), table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_relation"), table_name="dependencies")
    op.drop_index("ix_dependencies_project_target", table_name="dependencies")
    op.drop_index("ix_dependencies_project_source", table_name="dependencies")
    op.drop_index(op.f("ix_dependencies_project_id"), table_name="dependencies")
    op.drop_table("dependencies")
    # ### end Alembic commands ###
